### PR TITLE
Convert remaining "colour" instances to "color"  

### PR DESCRIPTION
**Pull request by mabruzzo**
Last week we pulled in a PR (I think it was #49) that changed instances of "colour" to "color". This updates the remaining instances in the VL+CT-related machinery.

### CODE REVIEW

**Comment by bwoshea** [comment]
@clairekope and @cbrummelsmith  I've added you as reviewers to this PR; could the second person who approves it also merge?

**Review by bwoshea — APPROVED** [review]
Straightforward change - looks good to me!

**Review by cbrummelsmith — APPROVED** [review]
Looks good to me.

**Review by clairekope — APPROVED** [review]
I love find and replace

**Pull request merged**
