### PR TITLE
Shorten testing

### PR DESCRIPTION
**Pull request by jobordner**
CircleCI tests have been failing due to timing out on individual tests.  While testing needs some more serious updating to bring everything back online again (unit tests, cosmology, etc.), this is intended as a quick fix to shorten the time of longer tests so that CircleCI doesn't time out.  With the current tests being run, that's just "adapt-L5", which does simple hydro on a 2D AMR mesh, and "mesh-balanced", which is obsolete and redundant with adapt-L5 (it doesn't test load balancing as its current categorization would indicate; "balanced" here refers to maintaining the 2-1 mesh refinement jump limit).  When cosmology tests get re-added back in they will need to be updated to shorten their times as well.

### CODE REVIEW

**Comment by bwoshea** [comment]
@jobordner this seems pretty straightforward, but it seems that none of the CircleCI tests actually ran on this PR - do you have any idea why?  As I look at the actual files, I don't see any reason why they wouldn't run...

**Review by bwoshea — APPROVED** [review]

**Comment by jobordner** [comment]
@bwoshea I'm not sure why they didn't run, maybe there were a couple of updates in quick succession which it didn't like.  I've pushed a small bugfix (see #98) to retrigger testing, and tests seem to be running now.

**Comment by bwoshea** [comment]
@jobordner awesome, thank you!

**Review by gregbryan — APPROVED** [review]
Looks good to me -- thanks James!

**Review by jwise77 — APPROVED** [review]
Looks good. Thanks James!

**Pull request merged**
