### PR TITLE
Fixes for restart bugs (issue #5)

### PR DESCRIPTION
**Pull request by jobordner**
This PR addresses two bugs associated with Issue #5:

1. corrupted strings written to parameters.libconfig files after a restart (bug fix by Matthew Abruzzo) 
2. EnzoBlock attribute values not getting written to HDF5 files after restart.

### CODE REVIEW

**Comment by bwoshea** [comment]
@jobordner could you please fix the merge conflicts so that we can merge this?  Thank you!

**Comment by mabruzzo** [comment]
I looked into this and the source of the merge conflict is really simple. The PR #53 simply moved `input/checkpoint_ppm-1.in` and `input/checkpoint_ppm-8.in` to `input/Checkpoint/checkpoint_ppm-1.in` and `input/Checkpoint/checkpoint_ppm-8.in`. The `include` paths were also tweaked accordingly.

This is trivial to resolve. @jobordner would you like me to take care of it?

**Comment by mabruzzo** [comment]
@jobordner Out of curiosity, do you have any idea why the tests failed the first time they were run after you made the latest commit? I saw that they were timeout bugs - do you think that they were just an anomaly?

**Comment by jobordner** [comment]
@mabruzzo The adapt-L5-P1 test hung, which shouldn't be related to any of the changes in this PR. There were also error messages from circleci about violating concurrency limits, maybe it was somehow using more cores than requested at some point during the testing. Both single and double precision tests failed (I think I only checked where in one, however). When I reran it with ssh it still seemed to be slow. Not sure what happened, but it's something to keep an eye on.

**Comment by mabruzzo** [comment]
Thanks. I'll file an issue about it so that if that kind of issue pops up again, we'll have a record of it

**Comment by bwoshea** [comment]
2 approves, I'm going to merge1

**Pull request merged**
