### PR TITLE
bugfix in test infrastructure

### PR DESCRIPTION
**Pull request by fearmayo**

### CODE REVIEW

**Review by bwoshea — APPROVED** [review]
Looks good to me!

**Review by pgrete — COMMENTED** [review]
Likely not related to this fix, but are some test failing on purpose and then reported successfully by the automated test?
https://app.circleci.com/pipelines/github/enzo-project/enzo-e/222/workflows/ce5c8576-7923-40fe-a00b-af0cd23d7b2e/jobs/535
```
Test run summary

   Test runs attempted: 57
   Test runs started:   29
   --------------------
   *** failed in startup: test/AmrPpm/test_adapt-L5-P1.unit
   *** failed in startup: test/Balance/test_balance_greedy.unit
   *** failed in startup: test/Balance/test_balance_none.unit
   *** failed in startup: test/Balance/test_balance_rand_cent.unit
   *** failed in startup: test/Balance/test_balance_refine.unit
   *** failed in startup: test/Balance/test_balance_rotate.unit
   *** failed in startup: test/BoundaryConditions/test_boundary_outflow-2d.unit
   *** failed in startup: test/BoundaryConditions/test_boundary_outflow-3d.unit
   *** failed in startup: test/BoundaryConditions/test_boundary_periodic-2d.unit
   *** failed in startup: test/BoundaryConditions/test_boundary_periodic-3d.unit
   *** failed in startup: test/BoundaryConditions/test_boundary_reflecting-2d.unit
   *** failed in startup: test/BoundaryConditions/test_boundary_reflecting-3d.unit
   *** failed in startup: test/MethodCosmology/test_method_cosmology-8.unit
   *** failed in startup: test/MethodGravity/test_method_gravity_cg-8.unit
   *** failed in startup: test/MethodHeat/test_method_heat-8.unit
   *** failed in startup: test/Output/test_output-headers.unit
   *** failed in startup: test/Output/test_output-stride-1.unit
   *** failed in startup: test/Output/test_output-stride-2.unit
   *** failed in startup: test/Output/test_output-stride-4.unit
   *** failed in startup: test/Particles/test_particle-amr-dynamic.unit
   *** failed in startup: test/Particles/test_particle-amr-static.unit
   *** failed in startup: test/Particles/test_particle-circle.unit
   *** failed in startup: test/Particles/test_particle-x.unit
   *** failed in startup: test/Particles/test_particle-xy.unit
   *** failed in startup: test/Particles/test_particle-y.unit
   *** failed in startup: test/Performance/test_initial_png.unit
   *** failed in startup: test/Restart/test_checkpoint_ppm-8.unit
   *** failed in startup: test/Restart/test_method_ppml-8.unit
   --------------------
   Test runs completed: 29

Exiting testing with success
Done.

CircleCI received exit code 0
```

**Comment by fearmayo** [comment]
> Likely not related to this fix, but are some test failing on purpose and then reported successfully by the automated test?
> https://app.circleci.com/pipelines/github/enzo-project/enzo-e/222/workflows/ce5c8576-7923-40fe-a00b-af0cd23d7b2e/jobs/535
> 
> ```
> Test run summary
> 
>    Test runs attempted: 57
>    Test runs started:   29
>    --------------------
>    *** failed in startup: test/AmrPpm/test_adapt-L5-P1.unit
>    *** failed in startup: test/Balance/test_balance_greedy.unit
>    *** failed in startup: test/Balance/test_balance_none.unit
>    *** failed in startup: test/Balance/test_balance_rand_cent.unit
>    *** failed in startup: test/Balance/test_balance_refine.unit
>    *** failed in startup: test/Balance/test_balance_rotate.unit
>    *** failed in startup: test/BoundaryConditions/test_boundary_outflow-2d.unit
>    *** failed in startup: test/BoundaryConditions/test_boundary_outflow-3d.unit
>    *** failed in startup: test/BoundaryConditions/test_boundary_periodic-2d.unit
>    *** failed in startup: test/BoundaryConditions/test_boundary_periodic-3d.unit
>    *** failed in startup: test/BoundaryConditions/test_boundary_reflecting-2d.unit
>    *** failed in startup: test/BoundaryConditions/test_boundary_reflecting-3d.unit
>    *** failed in startup: test/MethodCosmology/test_method_cosmology-8.unit
>    *** failed in startup: test/MethodGravity/test_method_gravity_cg-8.unit
>    *** failed in startup: test/MethodHeat/test_method_heat-8.unit
>    *** failed in startup: test/Output/test_output-headers.unit
>    *** failed in startup: test/Output/test_output-stride-1.unit
>    *** failed in startup: test/Output/test_output-stride-2.unit
>    *** failed in startup: test/Output/test_output-stride-4.unit
>    *** failed in startup: test/Particles/test_particle-amr-dynamic.unit
>    *** failed in startup: test/Particles/test_particle-amr-static.unit
>    *** failed in startup: test/Particles/test_particle-circle.unit
>    *** failed in startup: test/Particles/test_particle-x.unit
>    *** failed in startup: test/Particles/test_particle-xy.unit
>    *** failed in startup: test/Particles/test_particle-y.unit
>    *** failed in startup: test/Performance/test_initial_png.unit
>    *** failed in startup: test/Restart/test_checkpoint_ppm-8.unit
>    *** failed in startup: test/Restart/test_method_ppml-8.unit
>    --------------------
>    Test runs completed: 29
> 
> Exiting testing with success
> Done.
> 
> CircleCI received exit code 0
> ```

Yeah there are still issues in the testing suite. This PR really just gets the tests running in the new mode. There are still a few bugs in there that need to be ironed out.

**Review by mabruzzo — APPROVED** [review]
Seems fine to me

**Comment by pgrete** [comment]
> > Likely not related to this fix, but are some test failing on purpose and then reported successfully by the automated test?
> > https://app.circleci.com/pipelines/github/enzo-project/enzo-e/222/workflows/ce5c8576-7923-40fe-a00b-af0cd23d7b2e/jobs/535
> > ```
> > Test run summary
> > 
> >    Test runs attempted: 57
> >    Test runs started:   29
> >    --------------------
> >    *** failed in startup: test/AmrPpm/test_adapt-L5-P1.unit
> >    *** failed in startup: test/Balance/test_balance_greedy.unit
> >    *** failed in startup: test/Balance/test_balance_none.unit
> >    *** failed in startup: test/Balance/test_balance_rand_cent.unit
> >    *** failed in startup: test/Balance/test_balance_refine.unit
> >    *** failed in startup: test/Balance/test_balance_rotate.unit
> >    *** failed in startup: test/BoundaryConditions/test_boundary_outflow-2d.unit
> >    *** failed in startup: test/BoundaryConditions/test_boundary_outflow-3d.unit
> >    *** failed in startup: test/BoundaryConditions/test_boundary_periodic-2d.unit
> >    *** failed in startup: test/BoundaryConditions/test_boundary_periodic-3d.unit
> >    *** failed in startup: test/BoundaryConditions/test_boundary_reflecting-2d.unit
> >    *** failed in startup: test/BoundaryConditions/test_boundary_reflecting-3d.unit
> >    *** failed in startup: test/MethodCosmology/test_method_cosmology-8.unit
> >    *** failed in startup: test/MethodGravity/test_method_gravity_cg-8.unit
> >    *** failed in startup: test/MethodHeat/test_method_heat-8.unit
> >    *** failed in startup: test/Output/test_output-headers.unit
> >    *** failed in startup: test/Output/test_output-stride-1.unit
> >    *** failed in startup: test/Output/test_output-stride-2.unit
> >    *** failed in startup: test/Output/test_output-stride-4.unit
> >    *** failed in startup: test/Particles/test_particle-amr-dynamic.unit
> >    *** failed in startup: test/Particles/test_particle-amr-static.unit
> >    *** failed in startup: test/Particles/test_particle-circle.unit
> >    *** failed in startup: test/Particles/test_particle-x.unit
> >    *** failed in startup: test/Particles/test_particle-xy.unit
> >    *** failed in startup: test/Particles/test_particle-y.unit
> >    *** failed in startup: test/Performance/test_initial_png.unit
> >    *** failed in startup: test/Restart/test_checkpoint_ppm-8.unit
> >    *** failed in startup: test/Restart/test_method_ppml-8.unit
> >    --------------------
> >    Test runs completed: 29
> > 
> > Exiting testing with success
> > Done.
> > 
> > CircleCI received exit code 0
> > ```
> 
> Yeah there are still issues in the testing suite. This PR really just gets the tests running in the new mode. There are still a few bugs in there that need to be ironed out.

Gotcha, then let's get this in.

**Review by pgrete — APPROVED** [review]

**Pull request merged**
