### PR TITLE
Build instruction for NASA Pleiades/Electra/Aitken

### PR DESCRIPTION
**Pull request by pgrete**
In addition to the specific build instruction I also started a new FAQ.
Currently it includes two common problem with respect to loading shared libraries (HDF seems to come up fairly often on the mailing list also for Enzo) and newer versions of `gfortran`.

This PR is ready for "review" in the sense that I need additional input as I'm pretty sure the resulting executable is not working as expected yet.

In addition to the Intel and Python issues on Pleiades described in the doc, here are the various problem I'm not sure how to solve yet (encountered following the instructions contained this PR):

1. When compiling Enzo-E the following warning shows (IIRC we talked about that before somewhere else but I didn't find it):
```
scons: warning: Two different environments were specified for target main_enzo.o,
	but they appear to have the same action: $CXX -o $TARGET -c $CXXFLAGS $CCFLAGS $_CCCOMCOM $SOURCES
File "/home1/pgrete/src/enzo-e/build-instructions-pleiades/Cello/SConscript", line 216, in <module>
```
I'm currently guessing that this is fine for G++ (as it says they result in the same action), but this could the cause of the error for Intel builds (where e.g., one env points at intel whereas the other assumes g++).

2. `make test` fails 

My best guess here is that this is due to an incompatible detection of the `mpirun` cmd on Pleiades, e.g., when run within a job `charmrun` goes into the branch triggered by an existing `PBS_NODEFILE` environment variable, but only tests for `mpirun` in that branch (whereas `mpiexec` is used on Pleiades).

E.g., when manually running one of the test commands:
```bash
/home1/pgrete/src/charm-v6.10.2/bin/charmrun ++ppn 4 +p4 bin/enzo-p ++local input/Boundary/boundary_reflecting-3d.in

Running on 1 processors:  +ppn 4 bin/enzo-p input/Boundary/boundary_reflecting-3d.in 
Charmrun> can not locate mpirun in order to run the program.
```
Also the `++local` part is currently hardcoded in some tests irrespective of the environment.

3. When properly (as far as I can tell) executed in SMP mode the result don't see quite correct with some random component:
For example, running `./bin/enzo-p +p4 +setcpuaffinity  input/HelloWorld/Hi.in` in the same session back to back may result in (shown `hi-de-0006.png`)

hi-de-0006_smp4_4

or

hi-de-0006_smp4_2

or

hi-de-0006_smp4

or throwing with `NaN`, e.g.,
```
 t   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 Falling back to a more diffusive Riemannsolver, HLL
 WARNING_MESSAGE
 flux_twoshock: eslice < 0:           24           1
                       NaN                       NaN  -4.3771853125000010E-044
                       NaN                       NaN                       NaN
                       NaN                       NaN                       NaN
                       NaN                       NaN                       NaN
 a                       NaN   1.0000000000000001E-030  0.16064201822615368        2.5100315347836513E-004                       NaN                       NaN
 b                       NaN                       NaN                       NaN
 c                       NaN                       NaN                       NaN
 d                       NaN                       NaN                       NaN
 e   9.9999999999999995E-021   9.9999999999999995E-021   9.9999999999999995E-021
 f                       NaN                       NaN                       NaN
 g   9.9999999999999995E-021   9.9999999999999995E-021   9.9999999999999995E-021
 h                       NaN                       NaN                       NaN
 i                       NaN                       NaN                       NaN
 j   9.9999999999999995E-021   9.9999999999999995E-021   9.9999999999999995E-021
 k   9.9999999999999995E-021   9.9999999999999995E-021   9.9999999999999995E-021
 l                       NaN                       NaN                       NaN
 m                       NaN                       NaN                       NaN
 n   9.9999999999999995E-021   9.9999999999999995E-021   9.9999999999999995E-021
 o   9.9999999999999995E-021   9.9999999999999995E-021   9.9999999999999995E-021
 p   1.0000000000000001E-030   1.0000000000000001E-030                       NaN
 q                       NaN                       NaN                       NaN
 r   0.0000000000000000        0.0000000000000000        0.0000000000000000     
 s  -4.3771853125000015E-014  -4.3771853125000009E-014                       NaN
 t   0.0000000000000000        0.0000000000000000                            NaN
 Falling back to a more diffusive Riemannsolver, HLL
 WARNING_MESSAGE
 yeuler_sweep eslice            1           1           1  -4.3771853125000009E-014
 yeuler_sweep eslice            2           1           1  -4.3771853125000021E-014
 yeuler_sweep eslice            3           1           1  -4.3771853125000015E-014
 yeuler_sweep eslice            4           1           1  -4.3771853125000009E-014
 xeuler_sweep eslice            1           1           1  -4.3771853125000009E-014
 xeuler_sweep eslice            2           1           1  -4.3771853125000021E-014
 xeuler_sweep eslice            3           1           1  -4.3771853125000015E-014
 xeuler_sweep eslice            4           1           1  -4.3771853125000009E-014
0 00009.01 Method Field density sum                  nan conserved to -nan digits of 53

```

4. Running with multiple mpi ranks across hosts Segfault

E.g., for 

```
0 00005.29 Performance simulation max-node-particles 0
0 00005.29 Performance simulation balance-eff-blocks-core 0.598958 (115/192)
0 00005.29 Performance simulation balance-eff-blocks-node 0.598958 (115/192)
------------- Processor 3 Exiting: Caught Signal ------------
Reason: Segmentation fault
[3] Stack Traceback:
  [3:0] enzo-p 0x6d8b40 LrtsBarrier()
  [3:1] libpthread.so.0 0x2aaaaace0c00 
  [3:2] enzo-p 0x919f92 FaceFluxes::load_data(char*)
  [3:3] enzo-p 0x918939 DataMsg::load_data(char*)
  [3:4] enzo-p 0x8cde0b MsgRefresh::unpack(void*)
  [3:5] enzo-p 0x60253e CkUnpackMessage(envelope**)
  [3:6] enzo-p 0x609b78 _processHandler(void*, CkCoreState*)
  [3:7] enzo-p 0x6d9cda CsdScheduleForever
  [3:8] enzo-p 0x6d9f46 CsdScheduler
  [3:9] enzo-p 0x6d81bf 
  [3:10] enzo-p 0x6d81ed 
  [3:11] libpthread.so.0 0x2aaaaacd86da 
  [3:12] libc.so.6 0x2aaaad11e2dd clone
MPT ERROR: Rank 3(g:3) is aborting with error code 1.
	Process ID: 85477, Host: r133i2n17, Program: /home1/pgrete/src/enzo-e/bin/enzo-p
	MPT Version: HPE MPT 2.23  09/13/20 02:52:52

MPT: --------stack traceback-------
------------- Processor 0 Exiting: Caught Signal ------------
Reason: Segmentation fault
[0] Stack Traceback:
  [0:0] enzo-p 0x6d8b40 LrtsBarrier()
  [0:1] libpthread.so.0 0x2aaaaace0c00 
  [0:2] enzo-p 0x919f92 FaceFluxes::load_data(char*)
  [0:3] enzo-p 0x918939 DataMsg::load_data(char*)
  [0:4] enzo-p 0x8cde0b MsgRefresh::unpack(void*)
  [0:5] enzo-p 0x60253e CkUnpackMessage(envelope**)
  [0:6] enzo-p 0x609b78 _processHandler(void*, CkCoreState*)
  [0:7] enzo-p 0x6d9cda CsdScheduleForever
  [0:8] enzo-p 0x6d9f46 CsdScheduler
  [0:9] enzo-p 0x6d81bf 
  [0:10] enzo-p 0x6d81ed 
  [0:11] libpthread.so.0 0x2aaaaacd86da 
  [0:12] libc.so.6 0x2aaaad11e2dd clone
MPT ERROR: Rank 0(g:0) is aborting with error code 1.
	Process ID: 28070, Host: r133i2n16, Program: /home1/pgrete/src/enzo-e/bin/enzo-p
	MPT Version: HPE MPT 2.23  09/13/20 02:52:52

MPT: --------stack traceback-------
```

Maybe I'm just doing sth horribly wrong due to lack of better knowledge...
Any advise is welcome.

### CODE REVIEW

**Comment by pgrete** [comment]
Following @mabruzzo hint that smp mode is not that well tested and not necessarily supported I removed those parts from the instruction.
However, even in full MPI mode the Segfault in the FaceFluxes remain:

```
------------- Processor 1 Exiting: Caught Signal ------------
Reason: Segmentation fault
[1] Stack Traceback:
  [1:0] enzo-p 0x6d1ba2 CmiTimerIsSynchronized
  [1:1] libc.so.6 0x2aaaace49320 
  [1:2] enzo-p 0x90e022 FaceFluxes::load_data(char*)
  [1:3] enzo-p 0x90c9de DataMsg::load_data(char*)
  [1:4] enzo-p 0x8c1e80 MsgRefresh::unpack(void*)
  [1:5] enzo-p 0x5ff3c2 CkUnpackMessage(envelope**)
  [1:6] enzo-p 0x606493 _processHandler(void*, CkCoreState*)
  [1:7] enzo-p 0x6d2858 CsdScheduleForever
  [1:8] enzo-p 0x6d2a71 CsdScheduler
  [1:9] enzo-p 0x6d1adb ConverseInit
  [1:10] enzo-p 0x5f8469 charm_main
  [1:11] libc.so.6 0x2aaaace34a35 __libc_start_main
  [1:12] enzo-p 0x58f789 _start
MPT ERROR: Rank 1(g:1) is aborting with error code 1
```

**Comment by pgrete** [comment]
FYI this issues does not seem to be (only) MPI related. 
I now rebuilt the stack again using the `verbs` backend in Charm++ and the FaceFluxes still segfault when using 4 processes:

```
------------- Processor 1 Exiting: Caught Signal ------------
Reason: segmentation violation
Suggestion: Try running with '++debug', or linking with '-memory paranoid' (memory paranoid requires '+netpoll' at runtime).
[1] Stack Traceback:
  [1:0] libc.so.6 0x2aaaacc29320 
  [1:1] enzo-p 0x947b15 FaceFluxes::load_data(char*)
  [1:2] enzo-p 0x9464e8 DataMsg::load_data(char*)
  [1:3] enzo-p 0x8f8d8f MsgRefresh::unpack(void*)
  [1:4] enzo-p 0x600ac6 CkUnpackMessage(envelope**)
  [1:5] enzo-p 0x606695 _processHandler(void*, CkCoreState*)
  [1:6] enzo-p 0x6f1763 CsdScheduleForever
  [1:7] enzo-p 0x6f1b8c CsdScheduler
  [1:8] enzo-p 0x6ef923 ConverseInit
  [1:9] enzo-p 0x5f9974 charm_main
  [1:10] libc.so.6 0x2aaaacc14a35 __libc_start_main
  [1:11] enzo-p 0x588989 _start
Fatal error on PE 1> segmentation violation
```

**Comment by jobordner** [comment]
I've fixed some SMP bugs in by` jobordner/new-output `and `new-output-merge` branches (the later is the former merged with `enzo-project/main`), these should help with running on Pleiades. This was with an MPI build of Charm++ and using gfortran; ifort has problems on other architectures (e.g. Frontera) so I'd stay away from it for now. I also used GNU g++, though icc should work ok. I compiled without grackle, and used non-smp mode.

I tried running regression tests in the `new-output` branch (not `new-output-merge` yet because regression testing is in a wonky state due to the premature pull of testing updates in `enzo-project/main` awhile back). Test results are here: http://client64-249.sdsc.edu/~bordner/enzo-e-test.nasa-pleiades.18/

Load balancing PPM AMR tests failed consistently in `interp2d`, though the control run without load balancing ran fine. I haven't seen this before. Since the control run was ok, so I'm not overly concerned.

The `adapt-L5` PPM AMR test ran without artifacts (it did have artifacts like the "Hi" test above before the SMP fixes), though the batch script exited without running the rest of the regression tests. I don't know why it exited early. (I've tried doing tests in interactive mode, but I keep getting logged out before the job starts).

So far it looks promising, though I don't know why the testing stopped before it was completed.

**Comment by jobordner** [comment]
Finally got all the regression tests run on Pleiades. The branch tested was `jobordner/new-output-merge`, but I used the `new-output` tests, so some newer tests were not included (in particular VL+CT tests, one of which is known to fail due to updated refresh not handling non-centered Fields correctly). Everything looks good, including cosmology tests, except load-balancing. See http://client64-249.sdsc.edu/~bordner/enzo-e-test.nasa-pleiades.26

**Comment by tumlinson** [comment]
Many of these problems have been fixed elsewhere (e.g. #139 is now merged) or are now moot that I wonder whether this particular should be closed and another opened to apply fixes to the Pleiades instructions as they currently exist.

**Comment by peeples** [comment]
I am going to close this with the plan that @tumlinson, @gsnyder206, and I will restart a new one that works for cmake.

**Pull request closed without merging**
