### PR TITLE
Multispecies cosmology

### PR DESCRIPTION
**Pull request by WillHicks96**
This contains changes necessary for using Grackle with cosmology problems (working out of @jobordner's `enzo-prolong` branch). The changes are as follows:

1. Small bug fix in `enzo_SolveHydroEquations.cpp`, where `colindex` was initialized as NULL and never updated, which caused segfaults when doing color field advection.
2. Adding color fields to refresh -- this is part of PR [#49](https://github.com/enzo-project/enzo-e/pull/49) 
3. Initialize chemistry fields in `enzo_EnzoInitialCosmology.cpp`
4. Explicitly passing cosmology units into Grackle because the first calls to `initialize_grackle_chemistry_data()` and  `setup_grackle_units()` happen before `enzo_units` are set to comoving

### CODE REVIEW

**Comment by bwoshea** [comment]
@WillHicks96 there's something funny with this PR - there are 289 changed files, which doesn't align with the nominal content of the PR.  Looking at the commits, this seems to include a lot of @jobordner 's WIP PR (#97 ), and probably some other stuff.  Would you mind issuing a cleaner PR?

**Comment by mabruzzo** [comment]
@WillHicks96 @bwoshea I'm pretty sure all of those file changes from PR #97 will persist until that PR is merged into `main`. So it's probably _not_ worth re-creating this PR until after that.

**Comment by bwoshea** [comment]
@mabruzzo thanks for pointing that out!  We probably want to hold off on merging this PR until #97 is merged in that case, but I think it's reasonable to review it in the interim.

**Comment by bwoshea** [comment]
@WillHicks96 Given that there are so many files modified (with the inclusion of files from PR #97 ), could you comment on the files that you modified for this specific PR?

**Comment by WillHicks96** [comment]
@bwoshea @mabruzzo Oh yes, I can definitely see how this is confusing--I added these changes on top of @jobordner's branch that includes the commits from PR [#97](https://github.com/enzo-project/enzo-e/pull/97), so the hundreds of file changes associated with that PR should go away once it goes through. 

The changes I made are limited only to the following 4 files: `enzo_EnzoMethodGrackle.cpp`, `enzo_EnzoInitialCosmology.cpp`, `enzo_SolveHydroEquations.cpp`, and `enzo_EnzoMethodPpm.cpp`

**Comment by mabruzzo** [comment]
Just a heads up: Because PR #97 branched off from the main branch so long ago, this doesn't seem to include some improvements that I previously introduced to ``EnzoMethodGrackle``.

It might take a little work to resolve these differences. I'm happy to help, if you run into any problems.

**Comment by peeples** [comment]
Hi Will, now that PR #97 has been merged, what is the status of this PR?

**Pull request closed without merging**
