### PR TITLE
WIP: Build with CMake

### PR DESCRIPTION
**Pull request by forrestglines**
WIP Branch to build Enzo-E with CMake instead of SCons. Currently not functional due to challenges getting Charm++ interface headers to build before compiling source files.

Suggested instructions to build with this directory structure:
```
- enzo-e-project
     --enzo-e (source)
     --build (build directory)
```
Bash instructions:
```bash
mkdir enzo-e-project
cd enzo-e-project

git clone https://github.com/forrestglines/enzo-e.git
cd enzo-e
git checkout cmake
cd ../

mkdir build
cd build

export CHARM_HOME= [my cello home]
export CELLO_ARCH=linux_gnu
export CELLO_PREC=double
cmake  -GNinja ../enzo-e
ninja
```
`ninja` is recommended due to speed and better feedback, although the default GNU `make` will work as well

### CODE REVIEW

**Comment by forrestglines** [comment]
I've implemented @mabruzzo suggestions to build the same Cello libraries that the SCons build creates. I also switched to explicitly specifying source files for each library instead of relying on globs. I inserted some code in the SCons build to identify all the source files.

However, I'm running into undefined references at the linking step that I don't understand. If I try to build the test `test_monitor`, I get

```
 ninja test_monitor
[1/1] Linking CXX executable src/test_monitor
FAILED: src/test_monitor 
: && /home/forrest/MSU/research/code/charm/multicore-linux-x86_64/bin/charmc -O3 -g -ffast-math -funroll-loops -fPIC -pedantic -module CommonLBs src/CMakeFiles/test_monitor.dir/Cello/test_Monitor.cpp.o  src/libmonitor_library.a  src/libtest_library.a  src/libcharm_library.a  src/libdata_library.a  src/libio_library.a  src/libmesh_library.a  src/libdata_library.a  src/libio_library.a  src/libmesh_library.a  /usr/lib/libpng.so  src/libdisk_library.a  src/libcello_library.a  src/libmonitor_library.a  src/libparallel_library.a  src/liberror_library.a  src/libmonitor_library.a  src/libparallel_library.a  src/liberror_library.a  /usr/lib/libboost_system.so.1.76.0  /usr/lib/libboost_filesystem.so.1.76.0  /usr/lib/libhdf5.so  /usr/lib/libsz.so  /usr/lib/libz.so  /usr/lib/libdl.so  -lm  src/libsimulation_library.a  src/libproblem_library.a  src/libexternal_library.a  -lgfortran  -lquadmath -o src/test_monitor && :
/usr/bin/ld: src/libdata_library.a(main_simulation.cpp.o): in function `_registermain_simulation()':
/home/forrest/MSU/research/code/enzo-e-project/build/src/main_simulation.def.h:1503: undefined reference to `_registersimulation()'
/usr/bin/ld: /home/forrest/MSU/research/code/enzo-e-project/build/src/main_simulation.def.h:1505: undefined reference to `_registermesh()'
collect2: error: ld returned 1 exit status
Fatal Error by charmc in directory /home/forrest/MSU/research/code/enzo-e-project/build
   Command g++ -rdynamic -D_REENTRANT -O3 -g -ffast-math -funroll-loops -fPIC -pedantic src/CMakeFiles/test_monitor.dir/Cello/test_Monitor.cpp.o moduleinit8252.o -L/home/forrest/MSU/research/code/charm/multicore-linux-x86_64/bin/../lib -lmoduleCommonLBs src/libmonitor_library.a src/libtest_library.a src/libcharm_library.a src/libdata_library.a src/libio_library.a src/libmesh_library.a src/libdata_library.a src/libio_library.a src/libmesh_library.a /usr/lib/libpng.so src/libdisk_library.a src/libcello_library.a src/libmonitor_library.a src/libparallel_library.a src/liberror_library.a src/libmonitor_library.a src/libparallel_library.a src/liberror_library.a /usr/lib/libboost_system.so.1.76.0 /usr/lib/libboost_filesystem.so.1.76.0 /usr/lib/libhdf5.so /usr/lib/libsz.so /usr/lib/libz.so /usr/lib/libdl.so -lm src/libsimulation_library.a src/libproblem_library.a src/libexternal_library.a -lgfortran -lquadmath -lckmain -lck -lmemory-default -lthreads-default -lconv-machine -lconv-core -ltmgr -lconv-util -lconv-partition -lhwloc_embedded -lm -lmemory-default -lthreads-default -lldb-rand -lconv-ldb -lpthread -lckqt -ldl -lmoduleCommonLBs -lmoduleNDMeshStreamer -lmodulecompletion -lz -lm /home/forrest/MSU/research/code/charm/multicore-linux-x86_64/bin/../lib/conv-static.o -o src/test_monitor returned error code 1
charmc exiting...
ninja: build stopped: subcommand failed.
```

The function  `_registermesh()'  gets generated by Charm++ in `./src/mesh.def.h`, which gets included in `cello_mesh.cpp.o`, which is bundled into `src/libcharm_library.a`, which is bundled into `src/libtest_library.a` (note that in the SCons build, `charm_library` was left out of `test_library but I don't understand).

It looks like `src/libcharm_library.a` is getting linked, and `_registermesh()` is in there
```
$ objdump  -t src/libcharm_library.a | grep registermesh
0000000000000238 l     O .bss   0000000000000004 _ZZ13_registermeshvE5_done
000000000000f9f0 g     F .text  000000000000052f _Z13_registermeshv
0000000000000000         *UND*  0000000000000000 _Z13_registermeshv
```
but it's undefined. It might be the order of the linked libraries in the command, but the object files are up front in the `charmc` call. 

@mabruzzo @pgrete

**Comment by pgrete** [comment]
I'll have a look.

**Comment by mabruzzo** [comment]
I'm also happy to take a look (but I probably won't get there until tomorrow).

**Comment by pgrete** [comment]
I now have the monitor test working.
I first  tried the "easy route" creating one large lib, which didn't end up going anywhere.
Inspired by @forrestglines separate static lib approach, I got it working.
Where should I push what I have? Create a PR to `forrestglines:cmake` branch or directly to to `enzo-project:main`?

**Comment by pgrete** [comment]
```cmake
[ 99%] Building Fortran object src/Enzo/CMakeFiles/enzo-e.dir/yeuler_sweep.F.o
[100%] Building Fortran object src/Enzo/CMakeFiles/enzo-e.dir/zeuler_sweep.F.o
[100%] Linking CXX executable ../../bin/enzo-e
[100%] Built target enzo-e
```
:tada: 

So far I only tested local build using gnu, e.g., via `cmake -DCHARM_ROOT=/home/pgrete/src/charm/build-cmake -DCMAKE_CXX_COMPILER=/home/pgrete/src/charm/build-cmake/bin/charmc -DCMAKE_Fortran_FLAGS="-fdefault-real-8 -fdefault-double-8 -ffixed-line-length-132"  .. && make`, which resulted in a working enzo-e exe (I'm seeing the Hi png output for test HelloWorld test).
The commit currently lives in my fork: https://github.com/pgrete/enzo-e/commit/48b19bbc465ed86e0a770015ecb8d94a8fa741d8
How shall we proceed? I'm curious to test this with ICC compilers on Pleiades.
Also, I didn't really bother tracking the dependencies in great details.
It may be worth discussing whether the separation that originally was present in the scons build is still desired/required or whether there could just be a single libcello containing all the components.

**Comment by forrestglines** [comment]
> I now have the monitor test working.
> I first tried the "easy route" creating one large lib, which didn't end up going anywhere.
> Inspired by @forrestglines separate static lib approach, I got it working.
> Where should I push what I have? Create a PR to `forrestglines:cmake` branch or directly to to `enzo-project:main`?

Great! The separate static libs were @mabruzzo's idea. You can push directly to my branch, or do a PR

**Comment by forrestglines** [comment]
> ```cmake
> [ 99%] Building Fortran object src/Enzo/CMakeFiles/enzo-e.dir/yeuler_sweep.F.o
> [100%] Building Fortran object src/Enzo/CMakeFiles/enzo-e.dir/zeuler_sweep.F.o
> [100%] Linking CXX executable ../../bin/enzo-e
> [100%] Built target enzo-e
> ```
> 
> tada
> 
> So far I only tested local build using gnu, e.g., via `cmake -DCHARM_ROOT=/home/pgrete/src/charm/build-cmake -DCMAKE_CXX_COMPILER=/home/pgrete/src/charm/build-cmake/bin/charmc -DCMAKE_Fortran_FLAGS="-fdefault-real-8 -fdefault-double-8 -ffixed-line-length-132" .. && make`, which resulted in a working enzo-e exe (I'm seeing the Hi png output for test HelloWorld test).
Everything builds and apparently runs on at least one machine. Nice!

> The commit currently lives in my fork: [pgrete@48b19bb](https://github.com/pgrete/enzo-e/commit/48b19bbc465ed86e0a770015ecb8d94a8fa741d8)

Go ahead and push that commit directly to `forrestglines:cmake`, I've added you and @mabruzzo as collaborators to my fork.

> How shall we proceed? I'm curious to test this with ICC compilers on Pleiades.

That would be the most interesting place to start.

> Also, I didn't really bother tracking the dependencies in great details.
> It may be worth discussing whether the separation that originally was present in the scons build is still desired/required or whether there could just be a single libcello containing all the components.

After going through those libraries, I don't think they're a great design. I would prefer a single cello library. We should also stick with explicitly listed source files and remove the files that aren't being compiled.

**Comment by forrestglines** [comment]
Oh,  pgrete@48b19bb is not a branch from mine, perhaps it does belong in a new PR.

How do you build it? I export `CHARM_ROOT` to my charm install but I still get
```
/home/forrest/MSU/research/code/enzo-e-project/enzo-e/src/Cello/cello.hpp:36:10: fatal error: charm++.h: No such file or directory
   36 | #include <charm++.h>
```

**Comment by pgrete** [comment]
Which version of Charm++ are you using and how did you install it?
I used  `7.0.0-rc` and directly used cmake to build charm++.

I'll push my changes to this branch shortly.

**Comment by pgrete** [comment]
I just pushed the changes including updating instructions.
I decided to go with the `glob` based approach and separate `CMakeLists.txt` as a minimum working example for now. We can reintroduce the more detailed source and header specifications later.

PS: I also removed the suggestion on using a build directory outside of the repository (but kept a comment that it is possible). From my point of view, new `cmake` users already have quite a bit to adapt to so having a build directory in the repo may feel more familiar. Anyway, I'm open for discussion on what we finally want to recommend.

**Comment by mabruzzo** [comment]
@pgrete It's fantastic that you were able to get everything to build!

I just wanted to offer my two cents on the following discussion:

>  >  Also, I didn't really bother tracking the dependencies in great details.
>  >  It may be worth discussing whether the separation that originally was present in the scons build is still desired/required or whether there could just be a single libcello containing all the components.
> 
> After going through those libraries, I don't think they're a great design. I would prefer a single cello library. We should also stick with explicitly listed source files and remove the files that aren't being compiled/

I want to voice my support for maintaining the existing structure of static libraries in this PR:
- I agree that the Cello layer could be structured slightly better, but I'm a little concerned that if we drop the current system and don't immediately reorganize the libraries (in the same PR) the different components might become more integrated with one-another in the near future (before we figure out how to better divide things back up in the future). Making the whole task  more difficult in the future.
- Presently, I think the current system makes development a lot faster in the `Cello` layer (although the experience depends exactly on what you're working on). Under the best of circumstances a change to a single header file may only require you to recompile a single static library.
- For comparison, currently a change to a single Enzo-E header file requires the entire layer to be recompiled (slowing things down a lot). 

I guess my recommendation is to keep the existing structure in the Cello layer, and as better organization becomes more apparent, we can slowly restructure the libraries. But again, that's just my 2 cents. (If you guys feel strongly about abandoning the current system we can definitely do that).

**Comment by pgrete** [comment]
I'm also in favor of just focusing on the build system for now (with feature parity to the current SCons system).
I'll report shortly on my attempts to compile with the intel stack on Pleiades.

**Comment by pgrete** [comment]
```bash
PBS r141i5n21:/nobackupp2/pgrete/src/enzo-e> ldd build-icc-mpi/bin/enzo-e 
	linux-vdso.so.1 (0x00002aaaaaacf000)
	libpngwriter.so => /nobackupp2/pgrete/src/enzo-e/build-icc-mpi/src/External/libpngwriter.so (0x00002aaaaaccf000)
	libpng16.so.16 => /nasa/pkgsrc/sles12/2021Q1/lib/libpng16.so.16 (0x00002aaaaaee5000)
	libz.so.1 => /nasa/pkgsrc/sles12/2021Q1/lib/libz.so.1 (0x00002aaaab116000)
	libhdf5.so.200 => /nasa/hdf5/1.12.0_serial/lib/libhdf5.so.200 (0x00002aaaab32c000)
	libsz.so.2 => /nasa/szip/2.1.1/lib/libsz.so.2 (0x00002aaaabdb0000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00002aaaabfc4000)
	libm.so.6 => /lib64/libm.so.6 (0x00002aaaac1c8000)
	libifport.so.5 => /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/libifport.so.5 (0x00002aaaac4c5000)
	libifcoremt.so.5 => /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/libifcoremt.so.5 (0x00002aaaaaaf7000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaaac6f3000)
	libmpi.so => /nasa/hpe/mpt/2.23/lib/libmpi.so (0x00002aaaac910000)
	libstdc++.so.6 => /nasa/pkgsrc/sles12/2021Q1/gcc10/lib64/libstdc++.so.6 (0x00002aaaacd4a000)
	libgcc_s.so.1 => /nasa/pkgsrc/sles12/2021Q1/gcc10/lib64/libgcc_s.so.1 (0x00002aaaad110000)
	libc.so.6 => /lib64/libc.so.6 (0x00002aaaad327000)
	libimf.so => /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/libimf.so (0x00002aaaad6cc000)
	libsvml.so => /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/libsvml.so (0x00002aaaadd4f000)
	libirng.so => /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/libirng.so (0x00002aaaaf81f000)
	libintlc.so.5 => /nasa/intel/Compiler/2020.4.304/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/libintlc.so.5 (0x00002aaaafb8a000)
	/lib64/ld-linux-x86-64.so.2 (0x00002aaaaaaab000)
	librt.so.1 => /lib64/librt.so.1 (0x00002aaaafe02000)
```

```
PBS r141i5n21:/nobackupp2/pgrete/src/enzo-e> mpiexec ./build-icc-mpi/bin/enzo-e ./input/HelloWorld/Hi.in 
Charm++> Running on MPI version: 3.1
Charm++> level of thread support used: -1 (desired: 0)
Charm++> Running in non-SMP mode: 4 processes (PEs)
Converse/Charm++ Commit ID: v7.0.0-rc1
Isomalloc> Synchronized global address space.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 2 hosts (2 sockets x 20 cores x 2 PUs = 80-way SMP)
Charm++> cpu topology info is gathered in 0.001 seconds.
0 00000.00 Parameters  Adapt:list = [ "slope" ]
0 00000.00 Parameters  Adapt:max_level = 3
0 00000.00 Parameters  Adapt:slope:field_list = [ "density" ]
0 00000.00 Parameters  Adapt:slope:max_coarsen = 2.000000000000000
0 00000.00 Parameters  Adapt:slope:min_refine = 10.00000000000000
0 00000.00 Parameters  Adapt:slope:type = "slope"
0 00000.00 Parameters  Boundary:type = "reflecting"
0 00000.00 Parameters  Domain:lower = [ 0.000000000000000 0.000000000000000 ]
0 00000.00 Parameters  Domain:upper = [ 1.000000000000000 1.000000000000000 ]
0 00000.00 Parameters  Field:gamma = 1.400000000000000
0 00000.00 Parameters  Field:ghost_depth = 4
0 00000.00 Parameters  Field:list = [ "density" "velocity_x" "velocity_y" "total_energy" "internal_energy" "pressure" ]
0 00000.00 Parameters  Group:conserved:field_list = [ "density" "internal_energy" "total_energy" ]
0 00000.00 Parameters  Group:list = [ "conserved" "make_field_conservative" ]
0 00000.00 Parameters  Group:make_field_conservative:field_list = [ "velocity_x" "velocity_y" "internal_energy" "total_energy" ]
0 00000.00 Parameters  Initial:list = [ "value" ]
0 00000.00 Parameters  Initial:value:density = [ 1.000000000000000 ((((((( 0.2000000000000000  <  x ) && ( x  <  0.3000000000000000 )) && ( 0.3000000000000000  <  y )) && ( y  <  0.7000000000000000 )) || (((( 0.4000000000000000  <  x ) && ( x  <  0.5000000000000000 )) && ( 0.3000000000000000  <  y )) && ( y  <  0.7000000000000000 ))) || (((( 0.6000000000000000  <  x ) && ( x  <  0.7000000000000000 )) && ( 0.3000000000000000  <  y )) && ( y  <  0.5000000000000000 ))) || (((( 0.2000000000000000  <  x ) && ( x  <  0.5000000000000000 )) && ( 0.4500000000000000  <  y )) && ( y  <  0.5500000000000000 ))) || (((( x  -  0.6500000000000000 ) * ( x  -  0.6500000000000000 )) + (( y  -  0.6000000000000000 ) * ( y  -  0.6000000000000000 ))) <  0.002500000000000000 ) 0.1250000000000000 ]
0 00000.00 Parameters  Initial:value:total_energy = [ 2.500000000000000 ((((((( 0.2000000000000000  <  x ) && ( x  <  0.3000000000000000 )) && ( 0.3000000000000000  <  y )) && ( y  <  0.7000000000000000 )) || (((( 0.4000000000000000  <  x ) && ( x  <  0.5000000000000000 )) && ( 0.3000000000000000  <  y )) && ( y  <  0.7000000000000000 ))) || (((( 0.6000000000000000  <  x ) && ( x  <  0.7000000000000000 )) && ( 0.3000000000000000  <  y )) && ( y  <  0.5000000000000000 ))) || (((( 0.2000000000000000  <  x ) && ( x  <  0.5000000000000000 )) && ( 0.4500000000000000  <  y )) && ( y  <  0.5500000000000000 ))) || (((( x  -  0.6500000000000000 ) * ( x  -  0.6500000000000000 )) + (( y  -  0.6000000000000000 ) * ( y  -  0.6000000000000000 ))) <  0.002500000000000000 ) 3.500000000000000 ]
0 00000.00 Parameters  Initial:value:velocity_x = 0.000000000000000
0 00000.00 Parameters  Initial:value:velocity_y = 0.000000000000000
0 00000.00 Parameters  Mesh:root_blocks = [ 4 4 ]
0 00000.00 Parameters  Mesh:root_rank = 2
0 00000.00 Parameters  Mesh:root_size = [ 80 80 ]
0 00000.00 Parameters  Method:list = [ "ppm" "flux_correct" ]
0 00000.00 Parameters  Method:ppm:courant = 0.8000000000000000
0 00000.00 Parameters  Method:ppm:diffusion = true
0 00000.00 Parameters  Method:ppm:dual_energy = false
0 00000.00 Parameters  Method:ppm:flattening = 3
0 00000.00 Parameters  Method:ppm:steepening = true
0 00000.00 Parameters  Output:density:colormap = [ 0.000000000000000 0.000000000000000 0.000000000000000 0.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 0.000000000000000 ]
0 00000.00 Parameters  Output:density:field_list = [ "density" ]
0 00000.00 Parameters  Output:density:image_size = [ 640 640 ]
0 00000.00 Parameters  Output:density:image_type = "data"
0 00000.00 Parameters  Output:density:name = [ "hi-de-%04d.png" "count" ]
0 00000.00 Parameters  Output:density:schedule:step = 10
0 00000.00 Parameters  Output:density:schedule:var = "cycle"
0 00000.00 Parameters  Output:density:type = "image"
0 00000.00 Parameters  Output:list = [ "density" "mesh_age" "mesh_level" ]
0 00000.00 Parameters  Output:mesh_age:colormap = [ 0.000000000000000 0.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 0.000000000000000 1.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 1.000000000000000 1.000000000000000 ]
0 00000.00 Parameters  Output:mesh_age:image_max = 1.000000000000000
0 00000.00 Parameters  Output:mesh_age:image_mesh_color = "age"
0 00000.00 Parameters  Output:mesh_age:image_min = 0.000000000000000
0 00000.00 Parameters  Output:mesh_age:image_size = [ 641 641 ]
0 00000.00 Parameters  Output:mesh_age:image_type = "mesh"
0 00000.00 Parameters  Output:mesh_age:name = [ "hi-mesh-age-%04d.png" "count" ]
0 00000.00 Parameters  Output:mesh_age:schedule:step = 10
0 00000.00 Parameters  Output:mesh_age:schedule:var = "cycle"
0 00000.00 Parameters  Output:mesh_age:type = "image"
0 00000.00 Parameters  Output:mesh_level:colormap = [ 0.000000000000000 0.000000000000000 0.000000000000000 0.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 1.000000000000000 0.000000000000000 1.000000000000000 0.000000000000000 0.000000000000000 ]
0 00000.00 Parameters  Output:mesh_level:image_mesh_color = "level"
0 00000.00 Parameters  Output:mesh_level:image_size = [ 641 641 ]
0 00000.00 Parameters  Output:mesh_level:image_type = "mesh"
0 00000.00 Parameters  Output:mesh_level:name = [ "hi-mesh-level-%04d.png" "count" ]
0 00000.00 Parameters  Output:mesh_level:schedule:step = 10
0 00000.00 Parameters  Output:mesh_level:schedule:var = "cycle"
0 00000.00 Parameters  Output:mesh_level:type = "image"
0 00000.00 Parameters  Stopping:time = 0.1000000000000000
0 00000.20 WARNING parameters_Config.cpp:928
0 00000.20 WARNING Config::read()
0 00000.20 WARNING output_axis[0] set to z
0 00000.20 WARNING parameters_Config.cpp:928
0 00000.20 WARNING Config::read()
0 00000.20 WARNING output_axis[1] set to z
0 00000.20 WARNING parameters_Config.cpp:928
0 00000.20 WARNING Config::read()
0 00000.20 WARNING output_axis[2] set to z
UNIT TEST BEGIN
0 00000.20  ==============================================
0 00000.20   
0 00000.20    .oooooo.             oooo  oooo            
0 00000.20   d8P'  `Y8b            `888  `888            
0 00000.20  888           .ooooo.   888   888   .ooooo.  
0 00000.20  888          d88' `88b  888   888  d88' `88b 
0 00000.20  888          888ooo888  888   888  888   888 
0 00000.20  `88b    ooo  888    .o  888   888  888   888 
0 00000.20   `Y8bood8P'  `Y8bod8P' o888o o888o `Y8bod8P' 
0 00000.20   
0 00000.20  A Parallel Adaptive Mesh Refinement Framework
0 00000.20   
0 00000.20    Laboratory for Computational Astrophysics
0 00000.20          San Diego Supercomputer Center
0 00000.20       University of California, San Diego
0 00000.20   
0 00000.20  See 'LICENSE_CELLO' for software license information
0 00000.20   
0 00000.20  BEGIN CELLO: Jul 06 11:35:02
0 00000.20 Define Simulation processors 4
0 00000.20 CHARM CkNumPes()           4
0 00000.20 CHARM CkNumNodes()         4
0 00000.20  BEGIN ENZO-E
0 00000.20 Memory bytes 184764 bytes_high 184818
0 00000.21 WARNING problem_InitialValue.cpp:147
0 00000.21 WARNING InitialValue::enforce_block
0 00000.21 WARNING Uninitialized field internal_energy
0 00000.21 WARNING problem_InitialValue.cpp:147
0 00000.21 WARNING InitialValue::enforce_block
0 00000.21 WARNING Uninitialized field pressure
0 00000.21 WARNING problem_InitialValue.cpp:147
0 00000.21 WARNING InitialValue::enforce_block
0 00000.21 WARNING Uninitialized field acceleration_x
0 00000.21 WARNING problem_InitialValue.cpp:147
0 00000.21 WARNING InitialValue::enforce_block
0 00000.21 WARNING Uninitialized field acceleration_y
0 00000.21 WARNING problem_InitialValue.cpp:147
0 00000.21 WARNING InitialValue::enforce_block
0 00000.21 WARNING Uninitialized field velocity_z
0 00000.21 WARNING problem_InitialValue.cpp:147
0 00000.21 WARNING InitialValue::enforce_block
0 00000.21 WARNING Uninitialized field acceleration_z
0 00000.25 Output writing image file ./hi-de-0000.png
0 00000.35 Output writing image file ./hi-mesh-age-0000.png
0 00000.49 Output writing image file ./hi-mesh-level-0000.png
0 00000.60  -------------------------------------
```

Just needed one tiny "hack" to overwrite the compiler used for linking in the `mpicxx` wrapper when called from the `charmc` wrapper.
I also added the processing of "configuration" files.
I'll add more configuration options (e.g., single/double precision) and support for Grackle tomorrow.

**Comment by pgrete** [comment]
And now with grackle support.
I missed the `#ifdef` in `enzo.ci` which resulted in many more hours than anticipated to get this working.
As a result I also started an FAQ with all the (not necessarily straightforward) compiler/linker errors I encountered.
I'll continue to add build options tomorrow.
I also noticed that the current test infrastructure is also linked to SCons so the "replacing the build system" may change more LOC than expected.

**Comment by forrestglines** [comment]
My previous issues were from using a `charm++` built with just `make`, changing to a `charm++` built with `cmake` resolved that issue. However, I'm still having trouble with the current commit.
```
$ Grackle_ROOT=/home/forrest/MSU/research/code/grackle/install/ CHARM_ROOT=/home/forrest/MSU/research/code/charm-cmake/installs/multicore-linux-x86_64/ cmake -GNinja ~/MSU/research/code/enzo-e-project/enzo-e/
-- Charm++ built in SMP mode
-- Found Grackle: /home/forrest/MSU/research/code/grackle/install/lib/libgrackle.so  
-- Cello/Enzo-E configured as follows:
USE_GRACKLE = ON
-- Configuring done
-- Generating done
-- Build files have been written to: /home/forrest/MSU/research/code/enzo-e-project/builds/multicore-linux-x86_64-Release
$ ninja                                                                                                                                                                                                                                                                                                                     
[275/328] Building Fortran object src/Enzo/CMakeFiles/enzo.dir/PPML_monot.F.o                                                                                                                                                                                                                                               
FAILED: src/Enzo/CMakeFiles/enzo.dir/PPML_monot.F.o                                                                                                                                                                                                                                                                         
/usr/bin/gfortran -I/home/forrest/MSU/research/code/enzo-e-project/enzo-e/src/Enzo -Isrc/Enzo/../Cello -I/home/forrest/MSU/research/code/enzo-e-project/enzo-e/src/Enzo/../Cello -I/home/forrest/MSU/research/code/enzo-e-project/enzo-e/src/Enzo -Isrc/Enzo -I/home/forrest/MSU/research/code/charm-cmake/installs/multicor
e-linux-x86_64/include -I/home/forrest/MSU/research/code/enzo-e-project/enzo-e/src/External -I/usr/include -I/home/forrest/MSU/research/code/grackle/install/include -O3 -DNDEBUG -O3 -Jsrc/Enzo -fpreprocessed -c src/Enzo/CMakeFiles/enzo.dir/PPML_monot.F-pp.f -o src/Enzo/CMakeFiles/enzo.dir/PPML_monot.F.o            
/home/forrest/MSU/research/code/enzo-e-project/enzo-e/src/Enzo/PPML_monot.F:226:37:                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                            
   80 |             uwl = Xmedian(u3(m),c1(m),u2(m))                                                                                                                                                                                                                                                                        
      |                          2                                                                                                                                                                                                                                                                                          
......                                                                                                                                                                                                                                                                                                                      
  226 |                   sjm = 2.e0*Xmedian(0.,u4(m)-u3(m),u3(m)-u2(m))                                                                                                                                                                                                                                                    
      |                                     1                                                                                                                                                                                                                                                                               
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(4)/REAL(8)).
...
```
Going back to earlier builds or using Make instead of Ninja didn't resolve the issues.

**Comment by forrestglines** [comment]
We can leave the library structure of Cello as is for now and change the use of glob later. I'd still prefer explicitly listing what source files are used since there are apparently files in Enzo that are not compiled and that the names of files are used to control which files are compiled into which libraries.

I don't see how separating the object files of the Cello layer into different libraries helps in this issue. If the header files for this libraries changed, you would still need to rebuild any source files that depend on them. The only advantage I can see to the current design is if linking multiple smaller libraries is faster than linking one library, if the smaller libraries can lead to a smaller binary even though the same `libcello` library is linked to, or if linking to only a few of the cello libraries during testing is leads to a noticeable speed up.

As an aside, using the Ninja build system that CMake allows us might alleviate some of the build times when making incremental changes to a large project. -- it's what Ninja's designed for.

**Comment by forrestglines** [comment]
> I also noticed that the current test infrastructure is also linked to SCons so the "replacing the build system" may change more LOC than expected.

Can we leave the SCons system in place so that we can build with both CMake and SCons for now?

**Comment by mabruzzo** [comment]
> I'd still prefer explicitly listing what source files are used since there are apparently files in Enzo that are not compiled and that the names of files are used to control which files are compiled into which libraries.

I agree that it might be nice to explicitly list which source files are used, on the grounds that it's more "idiomatic" CMake. Out of curiosity, which files in Enzo are not compiled? At this point, I think almost all of the unused FORTRAN files have been removed.

> I don't see how separating the object files of the Cello layer into different libraries helps in this issue. If the header files for this libraries changed, you would still need to rebuild any source files that depend on them. The only advantage I can see to the current design is if linking multiple smaller libraries is faster than linking one library, if the smaller libraries can lead to a smaller binary even though the same `libcello` library is linked to, or if linking to only a few of the cello libraries during testing is leads to a noticeable speed up

As you mention, the ability to avoid relinking/rebuild smaller libraries during development is an advantage. In particular, it makes the process much faster when you are refactoring/developing features in the Cello layer that you are then testing with a unit test. I've definitely found this useful. And since the build system already works in this way, my inclination is to maintain it (but maybe this should be revisited after this PR?). 

Upon reflection, the "main advantage" that I had been thinking about actually relates to Cello/Enzo-E's existing conventions for including header files. By convention almost every source file in a library has a corresponding header file, and each of these header files (and the header files from dependent libraries) are effectively included into every source file of a library. As a consequence of these conventions: 
- changing any header file in the enzo layer means that every object file in that layer must be recompiled (since only a single library is used).
-  In contrast, changing a header file in the Cello layer does not necessarily require that everything is recompiled. On

Only now, after thinking this through do I realize that this "main advantage" is unrelated to how we link the object files together (I'm assuming that charm++ "modules" don't introduce additional complexities to linking).

> As an aside, using the Ninja build system that CMake allows us might alleviate some of the build times when making incremental changes to a large project. -- it's what Ninja's designed for.

Yeah, that might definitely be interesting.

**Comment by peeples** [comment]
Hey @forrestglines I think this PR is now super-ceded by [PR #139](https://github.com/enzo-project/enzo-e/pull/139) -- I'll assign you as a reviewer over there, and we can close out this PR.

**Pull request closed without merging**
